development:
  adapter: postgresql
  encoding: unicode
  database: harrys_scraper_proxy_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: harrys_scraper_proxy_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: harrys_scraper_proxy
  pool: 5
